#!/bin/bash

sudo apt install yad
if yad --window-icon=package --image=package --title="Installer" --text='Welcome to the installer! This will automatically install the application on your computer. Click "OK" to continue the installation. Otherwise, click "Cancel" to exit.' --width=300 --height=300
then
	(
	#installation instructions
	) |
	yad --progress --center --window-icon=package --title="Installing..." --progress-text="Installing the application..." --pulsate --auto-close --auto-kill --no-buttons --width=450 --height=100
	zenity --info --icon-name=emblem-default --title="Success" --text="Installation complete." --width=300
fi
